CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;

CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name character varying NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

Create Table if not exists public.inventory
(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying not null,
	inv_model character varying not null,
	inv_year character(4) not null,
	inv_description text not null,
	inv_image character varying not null,
	inv_thumbnail character varying not null,
	inv_price numeric(9,0) not null,
	inv_miles integer not null,
	inv_color character varying not null,
	classification_id integer not null,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

Alter table if exists public.inventory
	add constraint fk_classification
	FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id)
	MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;
	
CREATE TABLE IF NOT EXISTS public.account
(
	account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	validate.addVehicleRules = ()=>{
    return [
      //classification_id, 
      body("classification_id")
      .isInt({min:1})
      .withMessage("Please select a valid classification."),
      //inv_make, 
      body("inv_make")
      .trim()
      .isLength({ min: 1 })
      .withMessage("Please provide the make of the vehicle."),
      //inv_model, 
      body("inv_model")
      .trim()
      .isLength({ min: 1 })
      .withMessage("Please provide the model of the vehicle."),
      //inv_year, 
      body("inv_year")
      .isInt({min:1900, max:2025})//(new Date).getFullYear +1})
      .withMessage("Please provide a four digit year."),
      //inv_description, 
      body("inv_description")
      .trim()
      .isLength({ min: 1 })
      .withMessage("Please provide a description of the vehicle"),
      //inv_image, 
      //inv_thumbnail, 
      //inv_price, 
      body("inv_price")
      .isInt({min:4})
      .withMessage("Please provide a valid price for the vehicle."),
      //inv_miles, 
      body("inv_miles")
      .isInt({min:1})
      .withMessage("Please provide the milage from the vehicle's odometer"),
      //inv_color 
      body("inv_color")
      .trim()
      .isLength({ min: 1 })
      .withMessage("Please provide the color of the vehicle."),
    ]
}
validate.checkAddVehicleData = async (req, res, next) => {
    const {  inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id } = req.body
    let errors = []
    errors = validationResult(req)
    if (!errors.isEmpty()) {
      let nav = await utilities.getNav()
      const classificationSelect = await utilities.buildClassificationSelect();
      res.render("./inventory/add-vehicle", {
        errors,
        title: "Add Vehicle",
        nav,
        classificationSelect,
        inv_make, 
        inv_model, 
        inv_year, 
        inv_description, 
        inv_image, 
        inv_thumbnail, 
        inv_price, 
        inv_miles, 
        inv_color,
        classification_id
      })
      return
    }
    next()
}


validate.checkUpdateVehicleData = async (req, res, next) => {
  const {  inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id, inv_id } = req.body
  let errors = []
  errors = validationResult(req)
  if (!errors.isEmpty()) {
    let nav = await utilities.getNav()
    const classificationSelect = await utilities.buildClassificationSelect(classification_id);
    res.render("./inventory/edit-inventory", {
      errors,
      title: "Add Vehicle",
      nav,
      classificationSelect,
      inv_make, 
      inv_model, 
      inv_year, 
      inv_description, 
      inv_image, 
      inv_thumbnail, 
      inv_price, 
      inv_miles, 
      inv_color,
      classification_id,
      inv_id
    })
    return
  }
  next()
}
	DEFAULT 'Client'::account_type,
	CONSTRAINT account_pkey PRIMARY KEY (account_id)
);


INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');

-- Data for table `inventory`

INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES   (
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
    '/images/camaro.jpg',
    '/images/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
  ), (
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through trafic during rush hour.',
    '/images/bat.jpg',
    '/images/bat-tn.jpg',
    65000,
    29887,
    'Black',
    1
  ), (
    'FBI',
    'Surveillance Van',
    '2016',
    'do you like police shows? You will feel right at home driving this van, come complete with survalence equipments for and extra fee of $2,000 a month. ',
    '/images/fbi.jpg',
    '/images/fbi-tn.jpg',
    20000,
    19851,
    'Green',
    1
  ), (
    'Dog ',
    'Car',
    '1997',
    'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.',
    '/images/dog.jpg',
    '/images/dog-tn.jpg',
    35000,
    71632,
    'Brown',
    1
  ), (
    'Jeep',
    'Wrangler',
    '2019',
    'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!',
    '/images/jeep-wrangler.jpg',
    '/images/jeep-wrangler-tn.jpg',
    28045,
    41205,
    'Orange',
    3
  ), (
    'Lamborghini',
    'Adventador',
    '2016',
    'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
    '/images/lambo-Adve.jpg',
    '/images/lambo-Adve-tn.jpg',
    417650,
    71003,
    'Blue',
    2
  ), (
    'Aerocar International',
    'Aerocar',
    '1963',
    'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
    '/images/aerocar.jpg',
    '/images/aerocar-tn.jpg',
    700000,
    18956,
    'Red',
    1
  ), (
    'Monster',
    'Truck',
    '1995',
    'Most trucks are for working, this one is for fun. this beast comes with 60in tires giving you tracktions needed to jump and roll in the mud.',
    '/images/monster.jpg',
    '/images/monster-tn.jpg',
    150000,
    3998,
    'purple',
    1
  ), (
    'Cadillac',
    'Escalade',
    '2019',
    'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
    '/images/escalade.jpg',
    '/images/escalade-tn.jpg',
    75195,
    41958,
    'Black',
    4
  ), (
    'GM',
    'Hummer',
    '2016',
    'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
    '/images/hummer.jpg',
    '/images/hummer-tn.jpg',
    58800,
    56564,
    'Yellow',
    4
  ), (
    'Mechanic',
    'Special',
    '1964',
    'Not sure where this car came from. however with a little tlc it will run as good a new.',
    '/images/ms.jpg',
    '/images/ms-tn.jpg',
    100,
    200125,
    'Rust',
    5
  ), (
    'Ford',
    'Model T',
    '1921',
    'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
    '/images/ford-modelt.jpg',
    '/images/ford-modelt-tn.jpg',
    30000,
    26357,
    'Black',
    5
  ), (
    'Mystery',
    'Machine',
    '1999',
    'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.',
    '/images/mm.jpg',
    '/images/mm-tn.jpg',
    10000,
    128564,
    'Green',
    1
  ),
  (
    'Spartan',
    'Fire Truck',
    '2012',
    'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.',
    '/images/fire-truck.jpg',
    '/images/fire-truck-tn.jpg',
    50000,
    38522,
    'Red',
    4
  ), (
    'Ford',
    'Crown Victoria',
    '2013',
    'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.',
    '/images/crown-vic.jpg',
    '/images/crown-vic-tn.jpg',
    10000,
    108247,
    'White',
    5
  );

update public.inventory
	Set inv_image = replace(inv_image, '/images', '/images/vehicles'), 
	inv_thumbnail = replace(inv_thumbnail, '/images', '/images/vehicles');

  
CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");


CREATE TABLE review (
    review_id SERIAL PRIMARY KEY,
    account_id INTEGER REFERENCES account(account_id),
    inv_id INTEGER REFERENCES inventory(inv_id),
    review_comment TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);